### ISSUE TITLE
Proposal for Movement Workshop in WorkshopRoom

### ISSUE THREAD

**Issue by chrishobcroft** [decentralizedcultureroom/movementroom#1]
From @chrishobcroft's friend Birte:

```
Hey dear Chris, 

soooo... here is the the concept of the workshop
my CV in german
my portfolio about artistic work in 2018

I asked Alice Rose to join in as a musician :) 

it wd be a great joy and wonderful experience to be part of the event. 

Please have a look at the concept. one is as a word one is as a pdf. 
If you think i should change something before sending it out to other. let me know. (MY ENGLISH ;)
It has some thought in general and then a schedule ( schedule all the times are just a first idea) 

love, birte
```

[Birte Hendricks_Lebenslauf_ ETH_ 2018 .pdf](https://github.com/decentralizedcultureroom/workshoproom/files/2330033/Birte.Hendricks_Lebenslauf_.ETH_.2018.pdf)
[concept Moving Room .pdf](https://github.com/decentralizedcultureroom/workshoproom/files/2330034/concept.Moving.Room.pdf)
[Portfolio_2018_ Birte Hendricks. pdf.pdf](https://github.com/decentralizedcultureroom/workshoproom/files/2330035/Portfolio_2018_.Birte.Hendricks.pdf.pdf)

**Comment by chrishobcroft** [comment]
[Alice Rose](https://www.youtube.com/watch?v=eAcgabDY7Gs)

**Comment by chrishobcroft** [comment]
@victoriapriester for your awareness.

@mariapaulafn this is some light reading for you, and budgetary approval, please.

**Comment by chrishobcroft** [comment]
Email on Wednesday 29 August:

```
Hello, 

find my new Budget in the concept. 

- One musician can t make it  - she is not in berlin. 
So i take 1 musician for saturday eve and i am only offering one workshop session each. 

Can you please send me a confirmation about the moving room concept / budget? 


Thank you! bests birte

Bests Birte  
```

[concept Moving Room .pdf](https://github.com/decentralizedcultureroom/workshoproom/files/2336458/concept.Moving.Room.pdf)

**Comment by chrishobcroft** [comment]
@mariapaulafn please can you confirm budget for this.

**Comment by mariapaulafn** [comment]
Yes confirmed via email
